name: PHP Lint, Build, and Push Workflow

# Ce workflow s'exécute sur un push vers la branche develop
on:
  push:
    branches:
      - develop

jobs:
  # Job 1 : Lint PHP files
  lint:
    name: Lint PHP Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run PHP lint
        run: |
          find . -type f -name "*.php" -exec php -l {} \;

  # Job 2 : Build Docker image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint  # Ce job dépend du job "lint"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build -t my-site-image:latest .

  # Job 3 : Push Docker image to Docker Hub
  push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job "build"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-site-image:latest ${{ secrets.DOCKER_USERNAME }}/my-site-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-site-image:latest

